failure-threshold: warning

override:
  error:
    - DL3002
    - DL3007
    - DL4006

  warning:
    - DL3025
    - DL3020
    - DL3059

  info:
    - DL3008
    - DL3013

trustedRegistries:
  - docker.io
  - ghcr.io
  - gcr.io
